version: '3.8'

services:
  wordpress:
    # image: wordpress:latest
    build: ./docker/wordpress
    env_file: .env
    container_name: ${SITE_NAME}-wordpress
    working_dir: /var/www/html/wp
    volumes:
      - ./web:/var/www/html
    ports:
      - '8081:80'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    env_file: .env
    container_name: ${SITE_NAME}-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/db_dump:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - '3307:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    env_file: .env
    container_name: ${SITE_NAME}-phpmyadmin
    links:
      - mysql
    ports:
      - '8000:80'
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
      - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
  php:
    build: ./docker/php
    container_name: ${SITE_NAME}-php
    volumes:
      - ./web:/var/www/html
      - ./${DEV_ROOT}/${THEME_PATH}:/var/www/html${THEME_PATH}
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - '8080:80'
    env_file: .env
    environment:
      - VIRTUAL_HOST=${VHOST}
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: ${SITE_NAME}-nginx_proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf:ro
  mailhog:
    image: mailhog/mailhog
    platform: linux/x86_64
    container_name: ${SITE_NAME}-mailhog
    ports:
      - '8025:8025'
      - '1025:1025'
volumes:
  db:
networks:
  default:
    name: ${SITE_NAME}-default
